### **Chapter 4: BRANCHING STATEMENTS**

In [1]:
import numpy as np
import math

**Q1.** Write a function *my_tip_calc(bill, party)*, where bill is the total cost of a meal and party is the number of people in the group. The tip should be calculated as 15% for a party strictly less than six people, 18% for a party strictly less than eight, 20% for a party less than 11, and 25% for a party 11 or more. A couple of test cases are given below.

def my_tip_calc(bill, party):

  *#write your function code here*
 
    return tips

In [2]:
def my_tip_calc(bill, party):
    if party <= 0:
        tips = "Error"
    elif party < 6:
        tips = 15/100*bill
    elif party < 8:
        tips = 18/100*bill
    elif party < 11:
        tips = 20/100*bill
    else:
        tips = 25/100*bill
    return tips

print(my_tip_calc(109.29,3))
print(my_tip_calc(109.29,7))
print(my_tip_calc(109.29,9))
print(my_tip_calc(109.29,12))

16.3935
19.6722
21.858000000000004
27.3225


**Q2.** Write a function *my_mult_operation(a, b, operation)*. The input argument, operation,is a string that is either "plus", "minus", "mult", "div", or "pow", and the function should compute: a + b, a − b, a∗b, a/b, and $a^b$ for the respective values for operation. A couple of test cases are given below.

def my_mult_operation(a, b, operation):
  
  *#write your function code here*
    
    return out

In [3]:
def my_mult_operation(a, b, operation):
    if operation == "plus":
        out = a + b
    elif operation == "minus":
        out = a - b
    elif operation == "mult":
        out = a*b
    elif operation == "div":
        out = a/b
    elif operation == "pow":
        out = a**b
    return out

In [4]:
x = np.array([1,2,3,4])
y = np.array([2,3,4,5])

print(my_mult_operation(x, y, "plus"))
print(my_mult_operation(x, y, "minus"))
print(my_mult_operation(x, y, "mult"))
print(my_mult_operation(x, y, "div"))
print(my_mult_operation(x, y, "pow"))

[3 5 7 9]
[-1 -1 -1 -1]
[ 2  6 12 20]
[0.5        0.66666667 0.75       0.8       ]
[   1    8   81 1024]


**Q3.**  Consider a triangle with vertices at (0, 0), (1, 0), and (0, 1). Write a function with the name *my_inside_triangle(x, y)*, where the output is the string "outside" if the point (x, y) is outside of the triangle, "border" if the point is exactly on the border of the triangle, and "inside" if the point is on the inside of the triangle.

def my_inside_triangle(x, y):

 *#write your function code here*

    return position

In [5]:
def my_inside_triangle(x, y):
    if x < 0 or y < 0:
        position = "outside"
    if x > 0 and y > 0:
        if (x + y) < 1:
            position = "inside"
        else:
            position = "outside"
    else:
        position = "border"
    return position

print(my_inside_triangle(.5,.5))
print(my_inside_triangle(.25,.25))
print(my_inside_triangle(5,5))

outside
inside
outside


**Q4.** Write a function *my_make_size10(x)*, where x is an array, and output is the first 10 elements of x if x has more than 10 elements, and output is the array x padded with enough zeros to make it length 10 if x has less than 10 elements.

def my_make_size10(x) :
  
  *#write your function code here*

    return size10

In [6]:
def my_make_size10(x):
    x = np.array(x)
    if len(x)>9:
        size10 = x[0:10]
    else:
        size10 = np.concatenate([x, np.zeros(10 - len(x))])
    return size10

print(my_make_size10(range(1,3)))
print(my_make_size10(range(1,15)))
print(my_make_size10([3, 6, 13, 4]))

[1. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 1  2  3  4  5  6  7  8  9 10]
[ 3.  6. 13.  4.  0.  0.  0.  0.  0.  0.]


**Q5.**  Can you write *my_make_size10* without using if-statements (i.e., using only logical and array operations)?

In [7]:
def my_make_size10_1(x):
    size10 = np.concatenate([x[:10], np.zeros(max(0, 10 - len(x)))] )
    return size10

print(my_make_size10_1(range(1, 3)))    
print(my_make_size10_1(range(1, 15)))   
print(my_make_size10_1([3, 6, 13, 4])) 

[1. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 3.  6. 13.  4.  0.  0.  0.  0.  0.  0.]


**Q6.** Write a function *my_letter_grader(percent)*, where the grade is the string "A+" if percent is greater than 97, "A" if percent is greater than 93, "A-" if percent is greater than 90, "B+" if percent is greater than 87, "B" if percent is greater than 83, "B-" if percent is greater than 80, "C+" if percent is greater than 77, "C" if percent is greater than 73, "C-" if percent is greater than 70, "D+" if percent is greater than 67, "D" if percent is greater than 63, "D-" if percent is greater than 60, and "F" for any percent less than 60. Grades exactly on the division should be included in the higher grade category.

def my_letter_grader(percent):
 
  *#write your function code here*
 
    return grade

In [8]:
def my_letter_grader(percent):
    if percent < 0 or percent > 100:
        grade = "Error"
    elif percent >= 97:
        grade = "A+"
    elif percent >= 93:
        grade = "A"
    elif percent >= 90:
        grade = "A-"
    elif percent >= 87:
        grade = "B+"
    elif percent >= 83:
        grade = "B"
    elif percent >= 80:
        grade = "B-"
    elif percent >= 77 :
        grade = "C+"
    elif percent >= 73:
        grade = "C"
    elif percent >= 70 :
        grade = "C-"
    elif percent >= 67 :
        grade = "D+"
    elif percent >= 63 :
        grade = "D"
    elif percent >= 60 :
        grade = "D-"
    else:
        grade = "F"
    return grade

print(my_letter_grader(97))
print(my_letter_grader(84))

A+
B


**Q7.** Most engineering systems have a built-in redundancy. That is, an engineering system has fail-safes incorporated into the design to accomplish its purpose. Consider a nuclear reactor whose temperature is monitored by three sensors. An alarm should go off if any two of the sensor readings disagree. Write a function *my_nuke_alarm(s1, s2, s3)*, where s1, s2, and s3 are the temperature readings for sensor 1, sensor 2, and sensor 3, respectively. The output should be the string "alarm!" if any two of the temperature readings disagree by strictly more than 10 degrees and "normal" otherwise.

def my_nuke_alarm(s1, s2, s3):
 
 *#write your function code here*
 
    return response

In [9]:
def my_nuke_alarm(s1, s2, s3):
    if abs(s1-s2)>10 or abs(s2-s3)>10 or abs(s3-s1)>10:
        response = "alarm!"
    else:
        response = "normal"
    return response

print( my_nuke_alarm(94,96,90))
print( my_nuke_alarm(94,96,80))
print( my_nuke_alarm(100,96,90))

normal
alarm!
normal


**Q8.**  Let Q(x) be the quadratic equation Q(x) = ax2 +bx +c for some scalar values a, b, and c. A root of Q(x) is an r such that Q(r)=0. The two roots of a quadratic equation can be described by the quadratic formula, which is

$r = \frac{−b±
 \sqrt{b^2 −4ac}}{2a}$.

 Aquadratic equation has either two real roots (i.e., b2 > 4ac), two imaginary roots (i.e., b2 < 4ac), or one root $r = \frac{−b}{2a}$. Write a function *my_n_roots(a, b, c)*, where a, b, and c are the coefficients of the quadratic Q(x). The function should return two values: *n_roots* and r.Also *n_roots* is 2 if Q has two real roots, 1 if Q has one root, −2 if Q has two imaginary roots, and r is an array containing the roots of Q.

def my_n_roots(a, b, c):

*#write your function code here*

    return n_roots, r

In [10]:
def my_n_roots(a, b, c):
    D = b**2 - 4*a*c
    if D > 0:
        n_roots = 2
        r = [(-b + math.sqrt(D))/(2*a), (-b - math.sqrt(D))/(2*a)]
    elif D == 0:
        n_roots = 1
        r = [-b/(2*a)]
    else:
        n_roots = -2
        x = -b/(2*a)
        y = math.sqrt(-D)/(2*a)
        r = [complex(x, y), complex(x, -y)]
    return n_roots, r

n_roots, r = my_n_roots(1, 0, -9)
print(n_roots, r)
n_roots, r = my_n_roots(3, 4, 5)
print(n_roots, r)
n_roots, r = my_n_roots(2, 4, 2)
print(n_roots, r)

2 [3.0, -3.0]
-2 [(-0.6666666666666666+1.1055415967851332j), (-0.6666666666666666-1.1055415967851332j)]
1 [-1.0]


**Q9.** Write a function my_split_function(f, g, a, b, x), where f and g are function objects f(x) and g(x), respectively. The output should be f(x) if x ≤ a, g(x) if x ≥ b, and 0 otherwise. Assume that b > a.

In [11]:
def my_split_function(f, g, a, b, x):
    if x <= a:
        return f(x)
    elif x >= b:
        return g(x)
    else:
        return 0
    
print(my_split_function(np.exp,np.sin,2,4,1))
print(my_split_function(np.exp,np.sin,2,4,3))
print(my_split_function(np.exp,np.sin,2,4,5))

2.718281828459045
0
-0.9589242746631385


*This is the **END** of this Exercise.*