### **Chapter 5: ITERATION**

In [1]:
import numpy as np
import math
import random

**Q1.** What will the value of y be after the following code is executed?

In [2]:
y = 0
for i in range(1000):
    for j in range(1000):
        if i == j:
            y += 1
            
y

1000

**Q2.** Write a function *my_max(x)* to return the maximum (largest) value in x. Do not use the built-in Python function *max*.


In [3]:
def my_max(x):
    max = 0
    for i in range(len(x)):
        if x[i] > max:
            max = x[i]
    print(max)
        
my_max(np.array([1,22,33,433,4,5,6,0]))

433


**Q3.**  Write a function *my_n_max(x, n)* to return a list consisting of the n largest elements of x. You may use Python’s max function. You may also assume that x is a one-dimensional list with no duplicate entries, and that n is a strictly positive integer smaller than the length of x.

def my_n_max(x, n):

 *#write your function code here*
 
    return out

In [4]:
def my_n_max(x, n):
    out = []
    for _ in range(n):
        out.append(max(x))
        x.remove(max(x))
    return out

x = [7, 9, 10, 5, 8, 3, 4, 6, 2, 1]
my_n_max(x, 3)

[10, 9, 8]

**Q4.**  Let m be a matrix of positive integers. Write a function *my_trig_odd_even(m)* to return an array q, where q[i, j] = sin(m[i, j]) if m[i, j] is even, and q[i, j] = cos(m[i, j]) if m[i, j] is odd.

In [5]:
def my_trig_odd_even(m):
    nrow, ncol = m.shape
    out = np.zeros((nrow, ncol))
    for i in range(nrow):
        for j in range(ncol):
            if m[i, j]%2 == 0:
                out[i, j] = np.sin(m[i, j])
            else:
                out[i, j] = np.cos(m[i, j])
    return out
    
print(f" Array q = {my_trig_odd_even(np.array([[1, 2, 3], [4, 5, 6]]))}")

 Array q = [[ 0.54030231  0.90929743 -0.9899925 ]
 [-0.7568025   0.28366219 -0.2794155 ]]


**Q5.** Let P be an m×p array and Q be a p×n array. As you will find later in this book, M = P × Q is defined as $M[i, j]= \sum^{p}_{k=1}P[i, k]·Q[k, j]$. Write a function *my_mat_mult(P, Q)* that uses for-loops to compute M, the matrix product of P * Q. Hint: You may need up to three nested for-loops. Do not use the function np.dot.

import numpy as np

 def my_mat_mult(P, Q):

 *#write your function code here*

    return M

In [6]:
def my_mat_mult(P, Q):
    nrow_1, ncol_1 = P.shape
    nrow_2, ncol_2 = Q.shape
    M = np.zeros((nrow_1, ncol_2))
    if ncol_1 == nrow_2:
        for i in range(nrow_1):
            for k in range(ncol_1):
                for j in range(ncol_2):
                    M[i, j] += P[i, k]*Q[k, j]
    else:
        M = "Invalid Input!"
    return M

P = np.ones((3, 3))
print(my_mat_mult(P, P))

P = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
Q = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
print(my_mat_mult(P, Q))


[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[30. 30. 30.]
 [70. 70. 70.]]


**Q6.**  The interest *i* on a principle, $P_0$, is a payment for allowing the bank to use your money. Compound interest is accumulated according to the formula $P_n = (1 + i)P_{n−1}$, where *n* is the compounding period, usually in months or years. Write a function *my_saving_plan(P0, i, goal)*, where the output is the number of years it will take *P0* to become *goal* at *i%* interest compounded annually.

def my_saving_plan(P0, i, goal):

 *#write your function code here*
 
    return years

In [7]:
def my_saving_plan(P0, i, goal):
    years = 0
    while P0 < goal:
        P0 = (1 + i)*P0
        years += 1
    return years

print(my_saving_plan(1000, 0.05, 2000))
print(my_saving_plan(1000, 0.07, 2000))
print(my_saving_plan(500, 0.07, 2000))

15
11
21


**Q7.** Write a function with *my_find(M)* where the output is a list of indices *i* and where *M[ i ]* is 1. You may assume that *M* is a list of only ones and zeros. Do not use the built-in Python function find.

In [8]:
def my_find(M):
    indices = [x for x in range(len(M)) if M[x]==1]
    return indices
        
M = [1, 0, 1, 1, 0]
my_find(M)

[0, 2, 3]

**Q8.** Assume you are rolling two six-sided dice, with each side having an equal chance of occurring. Write a function *my_monopoly_dice()* where the output is the sum of the values of the two dice thrown but with the following extra rule: if the two dice rolls are the same, then another roll is made, and the new sum added to the running total. For example, if the two dice show 3 and 4, then the running total should be 7. If the two dice show 1 and 1, then the running total should be 2 plus the total of another throw. Rolls stop when the dice rolls are different.

In [9]:
def my_monopoly_dice():
    i = j = out = 0
    while i==j:
        i = random.choice(range(1,7))
        j = random.choice(range(1,7))
        out += (i+j)
    return out

print(my_monopoly_dice())
print(my_monopoly_dice())
print(my_monopoly_dice())

6
10
4


**Q9.**  A number is prime if it is divisible without remainder only by itself and 1. The number 1 is not a prime. Write a function *my_is_prime(n)*, where the output is 1 if *n* is prime and 0 is otherwise. Assume that *n* is a strictly positive integer.

In [10]:
def my_is_prime(n):
    nfac = 0
    for i in range(1, 1+n):
        if n%i == 0:
            nfac += 1
    if nfac == 2:
        return 1
    else:
        out = 0
    return out

print(my_is_prime(1))
print(my_is_prime(4))
print(my_is_prime(1001107))

0
0


1


**Q10.** Write a function *my_n_primes(n),* where prime is a list of the first n primes. Assume that *n* is a strictly positive integer.

In [11]:
def my_n_primes(n):
    prime = []
    i = 0
    while len(prime) < n:
        i += 1
        if my_is_prime(i) == 1:
            prime.append(i)
    return prime

print(f"Prime List = {my_n_primes(25)}")

Prime List = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


**Q11.** Write a function *my_n_fib_primes(n)*, where the output *fib_primes* is a list of the first n numbers that are both a Fibonacci number and a prime. Note that 1 is not prime. Hint: Do not use the recursive implementation of Fibonacci numbers. A function to compute Fibonacci numbers is presented in **Section 6.1**. You may use the code freely.

def my_n_fib_primes(n): 

*#write your function code here*
   
    return fib_primes


In [12]:
def my_n_fib_primes(n):
    fib = [1, 1]
    fib_primes = []
    while len(fib_primes) < n:
        nfib = fib[-1] + fib[-2]
        fib.append(nfib)
        if my_is_prime(nfib):
            fib_primes.append(nfib)
    return fib_primes

print(my_n_fib_primes(3))
print(my_n_fib_primes(8))

[2, 3, 5]
[2, 3, 5, 13, 89, 233, 1597, 28657]


**Q12.** Write a function *my_trig_odd_even(M)*, where the output $Q[i,j] = sin(\frac{π}{M[i,j]})$ if M[i, j] is odd, and $Q[i,j] = cos(\frac{π}{M[i,j]})$ if M[i, j] is even. Assume that M is a two-dimensional array of strictly positive integers.

def my_trig_odd_even(M):

 *#write your function code here*

    return Q

In [ ]:
def my_trig_odd_even(M):
    nrow, ncol = M.shape
    Q = np.zeros((nrow, ncol))
    for i in range(nrow):
        for j in range(ncol):
            if M[i, j]%2 == 0:
                Q[i, j] = np.cos(np.pi/M[i, j])
            else:
                Q[i, j] = np.sin(np.pi/M[i, j])
    return Q

print(my_trig_odd_even(np.array([[3, 4], [6, 7]])))

[[0.8660254  0.70710678]
 [0.8660254  0.43388374]]


**Q13.**  Let C be a square connectivity array containing zeros and ones. Point i has a connection to point j or i is connected to j if *C[i, j] = 1*. Note that connections in this context are one-directional, meaning *C[i, j]* is not necessarily the same as *C[j, i]*. For example, think of a one-way street from point A to point B. If A is connected to B, then B is not necessarily connected to A. Write a function *my_connectivity_mat_2_dict(C, names)*, where C is a connectivity array and names is a list of strings that denote the name of a point. That is, *names[i]* is the name of the name of the $i^{th}$ point. The output variable *node* should be a dictionary with the key as the string in *names*, and value is a vector containing the indices *j*, such that *C[i, j] = 1*. In other words, it is a list of points that point i is connected to.

def my_connectivity_mat_2_dict(C, names):

 *#write your function code here*
    
    return node

In [14]:
def my_connectivity_mat_2_dict(C, names):
    node = {}
    for i in range(len(names)):
        connections = []
        for j in range(len(names)):
            if C[i, j] == 1:
                connections.append(j+1)
        node[names[i]] = connections
    return node

C = np.array([[0, 1, 0, 1], [1, 0, 0, 1], [0, 0, 0, 1], [1, 1, 1, 0]])
names = ["Los Angeles", "New York", "Miami", "Dallas"]
node = my_connectivity_mat_2_dict(C, names)
for names in node:
    print(f"node[{names}] = {node[names]}")

node[Los Angeles] = [2, 4]
node[New York] = [1, 4]
node[Miami] = [4]
node[Dallas] = [1, 2, 3]


**Q14.** Turn the list *words* of lower case characters to upper case using the list comprehension.

In [15]:
words = ["test", "data", "analyze"]
words = [x.upper() for x in words]

words

['TEST', 'DATA', 'ANALYZE']

*This is the **END** of this Exercise.*