### **Chapter 2:  VARIABLES AND BASIC DATA STRUCTURES**

In [1]:
import numpy as np
import math

**Q1.** Assign the value 2 to the variable x and the value 3 to the variable y. Clear just the variable x.

In [2]:
x = 2
y = 3
del x

**Q2.** Write a line of code that generates the following error:

_NameError: name "x" is not defined_

In [3]:
# x

#OUTPUT:
# ---------------------------------------------------------------------------
# NameError                                 Traceback (most recent call last)
# Cell In[4], line 1
# ----> 1 x

# NameError: name 'x' is not defined

**Q3.** Let _x = 10_ and _y = 3_. Write a line of code that will make each of the following assignments.

_u=x+y_

_v = xy_

_w = x/y_

_z = sin(x)_

_r = 8sin(x)_

_s = 5sin(xy)_

_p = x**y_

In [4]:
x = 10
y = 3

u = x + y
v = x * y
w = x / y
z = math.sin(x)
r = 8 * math.sin(x)
s = 5 * math.sin(x * y)
p = x ** y

print(u, v, w, z, r, s, p)

13 30 3.3333333333333335 -0.5440211108893698 -4.352168887114958 -4.940158120464309 1000


**Q4.** Show all the variables in the *Jupyter notebook* after you finish Problem 3.

In [5]:
%whos

Variable   Type      Data/Info
------------------------------
math       module    <module 'math' (built-in)>
np         module    <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
p          int       1000
r          float     -4.352168887114958
s          float     -4.940158120464309
u          int       13
v          int       30
w          float     3.3333333333333335
x          int       10
y          int       3
z          float     -0.5440211108893698


**Q5.** Assign string "123" to the variable S. Convert the string into a float type and assign the output to the variable N. Verify that S is a string and N is a float using the type function.

In [6]:
S = "123"
N = float(S)

In [7]:
type(S)

str

In [8]:
type(N)

float

**Q6.**  Assign the string "HELLO" to the variable s1 and the string "hello" to the variable s2.Use the == operator to show that they are not equal. Use the == operator to show that s1 and s2 are equal if the lower method is used on s1. Use the == operator to show that s1 and s2 are equal if upper method is used on s2.

In [9]:
s1 = "HELLO"
s2 = "hello"

In [10]:
s1.lower() == s2

True

In [11]:
s1 == s2.upper()

True

**Q7.**  Use the print function to generate the following strings:

•    The word "Engineering" has 11 letters.

•    The word "Book" has 4 letters.

In [12]:
print('• The word "Engineering" has', len("Engineering"), 'letters.')
print('• The word "Book" has', len("Book"), 'letters.')

• The word "Engineering" has 11 letters.
• The word "Book" has 4 letters.


**Q8.**  Check if "Python" is in "Python is great!".

In [13]:
"Python" in "Python is great!"

True

**Q9.**  Get the last word "great" from "Python is great!"

In [14]:
"Python is great!".split()[-1]

'great!'

**Q10.** Assign list [1, 8, 9, 15] to a variable list_a and insert 2 at index 1 using the insert method. Append 4 to the list_a using the append method.

In [15]:
list_a = [1, 8, 9, 15]
list_a.insert(1, 2)
list_a.append(4)

list_a

[1, 2, 8, 9, 15, 4]

**Q11.** Sort the list_a in problem 10 in ascending order

In [16]:
sorted(list_a)  # list_a.sort()
list_a

[1, 2, 8, 9, 15, 4]

**Q12.** Turn "Python is great!" into a list.

In [17]:
print(list("Python is great!"))

['P', 'y', 't', 'h', 'o', 'n', ' ', 'i', 's', ' ', 'g', 'r', 'e', 'a', 't', '!']


**Q13.** Create one tuple with element "One", 1 and assign it to tuple_a.

In [18]:
tuple_a = ("One", 1)

**Q14.** Get the second element in the tuple_a in Problem 13.

In [19]:
tuple_a[1]

1

**Q15.** Get the unique element from (2, 3, 2, 3, 1, 2, 5).

In [20]:
set([2, 3, 2, 3, 1, 2, 5])

{1, 2, 3, 5}

**Q16.** Assign (2, 3, 2) to set_a, and (1,2,3) to set_b. Obtain the following:

• union of set_a and set_b

• intersection of set_a and set_b

• difference of set_a to set_b using difference method


In [21]:
set_a = (2, 3, 2)
set_b = (1, 2, 3)

In [22]:
set(set_a).union(set(set_b))

{1, 2, 3}

In [23]:
set(set_a).intersection(set(set_b))

{2, 3}

In [24]:
set(set_a).difference(set(set_b))

set()

In [25]:
set(set_b).difference(set(set_a))

{1}

**Q17.** Create a dictionary that has the keys"A","B","C"with values"a","b","c"individually. Print all the keys in the dictionary.

In [26]:
dict = {"A":'a', "B":'b', "C":'c'}
dict.keys()

dict_keys(['A', 'B', 'C'])

**Q18.**  Check if key "B" is in the dictionary defined in Problem17.

In [27]:
"B" in dict

True

In [28]:
"B" in dict.keys()

True

**Q19.** Create array x and y, where x = [1, 4, 3, 2, 9, 4] and y = [2, 3, 4, 1, 2, 3]. Compute the assignments from Problem 3.

In [29]:
import numpy as np
x = np.array([1, 4, 3, 2, 9, 4])
y = np.array([2, 3, 4, 1, 2, 3])

print(x+y)
print(x*y)
print(x/y)
print(np.sin(x))
print(8*np.sin(x))
print(5*np.sin(x*y))
print(x**y)

[ 3  7  7  3 11  7]
[ 2 12 12  2 18 12]
[0.5        1.33333333 0.75       2.         4.5        1.33333333]
[ 0.84147098 -0.7568025   0.14112001  0.90929743  0.41211849 -0.7568025 ]
[ 6.73176788 -6.05441996  1.12896006  7.27437941  3.29694788 -6.05441996]
[ 4.54648713 -2.68286459 -2.68286459  4.54648713 -3.75493623 -2.68286459]
[ 1 64 81  2 81 64]


**Q20.** Generate an array with size 100 evenly spaced between −10 to 10 using linspace function in NumPy.

In [30]:
np.linspace(-10, 10, 100)

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

**Q21.**  Let array_a be an array [-1, 0, 1, 2, 0, 3]. Write a command that will return an array consisting of all the elements of array_a that are larger than zero. Hint: Use logical expression as the index of the array.

In [31]:
array_a = np.array([-1, 0, 1, 2, 0, 3])
array_a[array_a > 0]

array([1, 2, 3])

**Q22.** Create an array y = 
\begin{bmatrix} 3 & 5 & 3 \\ 2 & 2 & 5 \\ 3 & 8 & 9 \end{bmatrix} 
and calculate its transpose.

In [32]:
y = np.array([[3, 5, 3], [2, 2, 5], [3, 8, 9]])
y.T

array([[3, 2, 3],
       [5, 2, 8],
       [3, 5, 9]])

**Q23.**  Create a 2×4 zero array.

In [33]:
array = np.zeros((2, 4))

**Q24.** Change the second column in the above array to 1.

In [34]:
array[:, 1] = 1
array

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.]])

**Q25.** Write a magic command to clear all the variables in the *Jupyter notebook*.

**Ans:-**  *%reset*  

*This is the **END** of this Exercise.*