### **Chapter 3:  FUNCTIONS**

In [1]:
import numpy as np
import math

**Q1.**  Recall that the hyperbolic sine,denoted by sinh, is $\frac{exp(x)−exp(−x)}{2}$. Write a function *my_sinh(x)* where the output y is the hyperbolic sine computed on x. Assume that x is a 1 by 1 float.

In [2]:
def my_sinh(x):
    return (math.exp(x) - math.exp(-x))/2

In [3]:
my_sinh(0)

0.0

In [4]:
my_sinh(1)

1.1752011936438014

In [5]:
my_sinh(2)

3.626860407847019

**Q2.** Write a function *my_checker_board(n)*, where the output m is an n×n array with the following form: m =
\begin{bmatrix}
1 & 0 & 1 & 0 & 1 \\
0 & 1 & 0 & 1 & 0 \\
1 & 0 & 1 & 0 & 1 \\
0 & 1 & 0 & 1 & 0 \\
1 & 0 & 1 & 0 & 1
\end{bmatrix}

 Note that: the upper-left element should always be 1.Assume that n is a strictly positive integer.

In [6]:
def my_checker_board(n):
    result = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            if (i+j)%2 == 0:
                result[i, j] = 1
    return result

In [7]:
my_checker_board(1)

array([[1.]])

In [8]:
my_checker_board(2)

array([[1., 0.],
       [0., 1.]])

In [9]:
my_checker_board(3)

array([[1., 0., 1.],
       [0., 1., 0.],
       [1., 0., 1.]])

In [10]:
my_checker_board(5)

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

**Q3.**  Write a function *my_triangle(b, h)* where the output is the area of a triangle with base, b, and height, h. Recall that the area of a triangle is one-half the base times the height. Assume that b and h are just 1 by 1 float numbers.

In [11]:
def my_triangle(b, h):
    return 1/2*b*h

In [12]:
my_triangle(1, 1)

0.5

In [13]:
my_triangle(2, 1)

1.0

In [14]:
my_triangle(12, 5)

30.0

**Q4.** Write a function *my_split_matrix(m)*, where m is an array, the output is a list [m1, m2] where m1 is
the left half of m, and m2 is the right half of m. In the case where there is an odd number of columns, the middle column should go to m1. Assume that m has at least two columns.

In [15]:
def my_split_matrix(m):
    ncol = m.shape[1]
    if ncol%2 == 0:
        num = ncol//2
    else:
        num = 1 + ncol//2
    m1 = m[:, :num]
    m2 = m[:, num:]
    return [m1, m2]

In [16]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
my_split_matrix(m)

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]])]

In [17]:
m = np.ones((5,5))
my_split_matrix(m)

[array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])]

In [18]:
m = np.zeros((4,4))
my_split_matrix(m)

[array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])]

**Q5.** Write a function *my_cylinder(r, h)*, where r and h are the radius and height of a cylinder, respectively, and the output is a list [s, v] where s and v are the surface area and volume of the same cylinder, respectively. Recall that the surface area of a cylinder is $2πr^2 + 2πrh$, and the volume is $πr^2h$. Assume that r and h are 1 by 1 floats.

In [19]:
def my_cylinder(r, h):
    s = 2*math.pi*r*(r+h)
    v = math.pi*r**2*h
    return [s, v]

In [20]:
my_cylinder(1, 5)

[37.69911184307752, 15.707963267948966]

In [21]:
my_cylinder(2, 4)

[75.39822368615503, 50.26548245743669]

**Q6.** Write a function *my_n_odds(a)*, where a is a one-dimensional array of floats and the output is the number of odd numbers in a.

In [22]:
def my_n_odds(a):
    return len(a[a%2 != 0])

In [23]:
my_n_odds(np.arange(100))

50

In [24]:
my_n_odds(np.arange(2, 100, 2))

0

**Q7.** Write a function *my_twos(m, n)* where the output is an m×n array of twos. Assume that m and n are strictly positive integers.

In [25]:
def my_twos(m, n):
    return np.full((m, n), 2)

In [26]:
my_twos(3, 2)

array([[2, 2],
       [2, 2],
       [2, 2]])

In [27]:
my_twos(1, 4)

array([[2, 2, 2, 2]])

**Q8.** Write a lambda function that takes in input x and y, and the output is the value of x - y.

In [28]:
my_diff = lambda x, y: x - y 

In [29]:
my_diff(937, 471)

466

**Q9.** Write a function *add_string(s1, s2)* where the output is the concatenation of the strings s1 and s2.

In [30]:
def add_string(s1, s2):
    return s1 + s2

In [31]:
s1 = add_string("Programming", " ")
s2 = add_string("is ", "fun!")
add_string(s1, s2)

'Programming is fun!'

**Q10.** Generate the following errors:

• TypeError: *fun( )* missing 1 required positional argument: "a"

• IndentationError: expected an indented block

In [32]:
# def fun(a):
#     return a

# fun()

# OUTPUT:
# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# Cell In[149], line 1
# ----> 1 fun()

#TypeError: fun() missing 1 required positional argument: 'a'

In [33]:
# def my_function():
# return 0

# OUTPUT:
# Cell In[152],   line 2
#    return 0
#    ^
# IndentationError: expected an indented block after function definition on line 1

**Q11.** Write a function *greeting(name, age)* where name is a string, age is a float, and the output is a string "Hi, my name is XXX and I am XXX years old." where XXX are the input name and age, respectively.

In [34]:
def greeting(name, age):
    print(f"Hi, my name is {name} and I am {age} years old.")

In [35]:
greeting("John", 26)

Hi, my name is John and I am 26 years old.


In [36]:
greeting("Kate", 19)

Hi, my name is Kate and I am 19 years old.


**Q12.** Let r1 and r2 be the radius of circles with the same center and let r2 > r1. Write a function *my_donut_area(r1, r2)* where the output is the area outside of the circle with radius r1 and inside the circle with radius r2. Make sure that the function is vectorized. Assume that r1 and r2 are one-dimensional arrays of the same size.

In [37]:
def my_donut_area(r1, r2):
    return np.pi*(r2**2 - r1**2)

In [38]:
my_donut_area(np.arange(1, 4), np.arange(2, 7, 2))

array([ 9.42477796, 37.69911184, 84.82300165])

**Q13.**  Write a function *my_within_tolerance(A, a, tol)* where the output is an array or list of the indices in A such that |A −a| <tol. Assume that A is a one-dimensional float list or array, and that a and tol are 1 by 1 floats.

In [39]:
def my_within_tolerance(A, a, tol):
    print(np.where(np.abs(np.array(A) - a) < tol)[0])

In [40]:
my_within_tolerance([0, 1, 2, 3], 1.5, 0.75)

[1 2]


In [41]:
my_within_tolerance(np.arange(0, 1.01, 0.01), 0.5, 0.03)

[47 48 49 50 51 52]


**Q14.** Write a function *bounding_array(A, top, bottom)* where the output is equal to the array A wherever bottom < A < top, the output is equal to bottom wherever A <= bottom, and the output is equal to top wherever A>=top.Assume that A is a one-dimensional float array and that top and bottom are 1 by 1 floats.

In [42]:
def bounding_array(A, top, bottom):
    A = np.array(A)
    A[A >= top] = top
    A[A <= bottom] = bottom
    print(A)

In [43]:
bounding_array(np.arange(-5, 6, 1), 3,-3)

[-3 -3 -3 -2 -1  0  1  2  3  3  3]


*This is the **END** of this Exercise.*